name: CI Pipeline

# ============================================================
# CI Pipeline
#
# Purpose:
# 1. Validate source code.
# 2. Execute unit and API tests.
# 3. Build Docker image.
# 4. Publish image to Docker Hub.
#
# Artifact Repository:
# Docker Hub
# ============================================================

# Trigger workflow on every push and pull request
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build-test-publish:

    # GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:

      # Checkout repository source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Python runtime
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install project dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Execute unit and API tests
      - name: Run Pytest Suite
        run: |
          pytest -v

      # Validate Dockerfile by building image
      - name: Build Docker Image
        run: |
          docker build -t diagnostics-api:${{ github.sha }} .

      # ------------------------------------------------------
      # Step 6 - Authenticate to Docker Hub.
      # Credentials are stored in GitHub Secrets.
      #
      # Required Secrets:
      # DOCKERHUB_USERNAME
      # DOCKERHUB_TOKEN
      # ------------------------------------------------------
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ------------------------------------------------------
      # Step 7 - Tag image for Docker Hub.
      # Repository format:
      # username/repository:tag
      #
      # github.sha provides a unique tag per commit.
      # ------------------------------------------------------
      - name: Tag Docker Image
        run: |
          docker tag \
          diagnostics-api:${{ github.sha }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/diagnostics-api:${{ github.sha }}


      # ------------------------------------------------------
      # Step 8 - Push image to Docker Hub.
      # Docker Hub now acts as the artifact repository.
      # ------------------------------------------------------
      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/diagnostics-api:${{ github.sha }}
